const {
  SAFETY_PIPELINE_TIMEOUT_HARD_LIMIT_MINUTES,
  PHASE_TIMEOUT_MAP,
  PHASE3_MAX_ITERATIONS_HARD_LIMIT,
} = require("../../config/runtimeConstants");

const PIPELINE_TIMEOUT_MINUTES_HARD_LIMIT = SAFETY_PIPELINE_TIMEOUT_HARD_LIMIT_MINUTES;

module.exports = {
  PIPELINE_TIMEOUT_MINUTES_HARD_LIMIT,
  PHASE_TIMEOUT_MAP,
  PHASE3_MAX_ITERATIONS_HARD_LIMIT,
};
