const VIDEO_SEGMENT_ALLOWED_INITIAL_DURATIONS = Object.freeze([4, 6, 8]);
const VIDEO_SEGMENT_MIN_TOTAL_SECONDS = Math.min(...VIDEO_SEGMENT_ALLOWED_INITIAL_DURATIONS);
const VIDEO_SEGMENT_DEFAULT_DURATION_SECONDS = Math.max(...VIDEO_SEGMENT_ALLOWED_INITIAL_DURATIONS);
const VIDEO_SEGMENT_EXTENSION_SECONDS = 7;
const VIDEO_SEGMENT_MAX_TOTAL_SECONDS = 148;
const VIDEO_SEGMENT_MAX_EXTENSIONS = 20;

const VIDEO_REFERENCE_IMAGES_MAX_COUNT = 3;

const VIDEO_POLL_DEFAULT_INTERVAL_MS = 10_000;
const VIDEO_POLL_DEFAULT_TIMEOUT_MS = 30 * 60 * 1000;
const VIDEO_POLL_DEFAULT_MAX_ATTEMPTS = 180;
const VIDEO_POST_PROCESSING_WAIT_DEFAULT_MS = 30_000;

const VIDEO_POST_PROCESSING_WAIT_MIN_MS = 1_000;
const VIDEO_POST_PROCESSING_WAIT_MAX_MS = 120_000;
const VIDEO_POLL_INTERVAL_MIN_MS = 1_000;
const VIDEO_POLL_INTERVAL_MAX_MS = 60_000;
const VIDEO_POLL_TIMEOUT_MIN_MS = 60_000;
const VIDEO_POLL_TIMEOUT_MAX_MS = 3_600_000;
const VIDEO_POLL_ATTEMPTS_MIN = 10;
const VIDEO_POLL_ATTEMPTS_MAX = 1_000;

const DEBATE_ROUNDS_DEFAULT = 3;
const DEBATE_ROUNDS_HARD_LIMIT = 10;

const SAFETY_DEFAULT_MAX_API_CALLS_PER_RUN = 200;
const SAFETY_DEFAULT_MAX_COST_PER_RUN_USD = 10;
const SAFETY_DEFAULT_PIPELINE_TIMEOUT_MINUTES = 30;
const SAFETY_PIPELINE_TIMEOUT_HARD_LIMIT_MINUTES = 60;

const SAFETY_MAX_API_CALLS_MIN = 50;
const SAFETY_MAX_API_CALLS_MAX = 500;
const SAFETY_MAX_COST_MIN_USD = 1;
const SAFETY_MAX_COST_MAX_USD = 100;
const SAFETY_PIPELINE_TIMEOUT_MIN_MINUTES = 10;

const SAFETY_COST_INPUT_RATE_PER_TOKEN_USD = 2.0 / 1_000_000;
const SAFETY_COST_OUTPUT_RATE_PER_TOKEN_USD = 12.0 / 1_000_000;

const PHASE_TIMEOUT_MAP = Object.freeze({
  1: { defaultMs: 5 * 60_000, hardLimitMs: 10 * 60_000 },
  2: { defaultMs: 5 * 60_000, hardLimitMs: 10 * 60_000 },
  3: { defaultMs: 20 * 60_000, hardLimitMs: 40 * 60_000 },
  4: { defaultMs: 3 * 60_000, hardLimitMs: 5 * 60_000 },
});

const PHASE3_MAX_ITERATIONS_HARD_LIMIT = 10;

module.exports = {
  VIDEO_SEGMENT_ALLOWED_INITIAL_DURATIONS,
  VIDEO_SEGMENT_MIN_TOTAL_SECONDS,
  VIDEO_SEGMENT_DEFAULT_DURATION_SECONDS,
  VIDEO_SEGMENT_EXTENSION_SECONDS,
  VIDEO_SEGMENT_MAX_TOTAL_SECONDS,
  VIDEO_SEGMENT_MAX_EXTENSIONS,
  VIDEO_REFERENCE_IMAGES_MAX_COUNT,
  VIDEO_POLL_DEFAULT_INTERVAL_MS,
  VIDEO_POLL_DEFAULT_TIMEOUT_MS,
  VIDEO_POLL_DEFAULT_MAX_ATTEMPTS,
  VIDEO_POST_PROCESSING_WAIT_DEFAULT_MS,
  VIDEO_POST_PROCESSING_WAIT_MIN_MS,
  VIDEO_POST_PROCESSING_WAIT_MAX_MS,
  VIDEO_POLL_INTERVAL_MIN_MS,
  VIDEO_POLL_INTERVAL_MAX_MS,
  VIDEO_POLL_TIMEOUT_MIN_MS,
  VIDEO_POLL_TIMEOUT_MAX_MS,
  VIDEO_POLL_ATTEMPTS_MIN,
  VIDEO_POLL_ATTEMPTS_MAX,
  DEBATE_ROUNDS_DEFAULT,
  DEBATE_ROUNDS_HARD_LIMIT,
  SAFETY_DEFAULT_MAX_API_CALLS_PER_RUN,
  SAFETY_DEFAULT_MAX_COST_PER_RUN_USD,
  SAFETY_DEFAULT_PIPELINE_TIMEOUT_MINUTES,
  SAFETY_PIPELINE_TIMEOUT_HARD_LIMIT_MINUTES,
  SAFETY_MAX_API_CALLS_MIN,
  SAFETY_MAX_API_CALLS_MAX,
  SAFETY_MAX_COST_MIN_USD,
  SAFETY_MAX_COST_MAX_USD,
  SAFETY_PIPELINE_TIMEOUT_MIN_MINUTES,
  SAFETY_COST_INPUT_RATE_PER_TOKEN_USD,
  SAFETY_COST_OUTPUT_RATE_PER_TOKEN_USD,
  PHASE_TIMEOUT_MAP,
  PHASE3_MAX_ITERATIONS_HARD_LIMIT,
};
