// Generated under Codex compliance with AGENTS.md (gemini-mimic)
const SETTINGS_DEFAULTS = {
  gemini: {
    apiKey: "",
    model: "gemini-3.1-pro-preview",
    temperature: 0.7,
    maxOutputTokens: 8192,
  },
  debate: {
    rounds: 3,
    parallelExperts: true,
  },
  video: {
    model: "veo-3.1-generate-preview",
    defaultDuration: 8,
    aspectRatio: "16:9",
    resolution: "720p",
    maxIterations: 3,
    extensionSeconds: 7,
    maxTotalSeconds: 148,
    postProcessingWait: 30000,
    pollInterval: 10000,
    pollTimeoutMs: 1800000,
    maxPollAttempts: 180,
    splitModel: "gemini-3.1-flash-lite-preview",
  },
  image: {
    model: "imagen-4.0-generate-001",
    maxReferenceSheets: 3,
  },
  ffmpeg: {
    path: "ffmpeg",
    defaultCodec: "libx264",
    defaultCrf: 23,
    defaultPreset: "medium",
  },
  experts: {
    phase1: {
      hook: true,
      story: true,
      cta: true,
      actionDesc: true,
      characterDesc: true,
    },
    phase3: {
      actionEval: true,
      characterEval: true,
      scenarioEval: true,
    },
  },
  safety: {
    maxApiCallsPerRun: 200,
    maxCostPerRunUsd: 10,
    pipelineTimeoutMinutes: 30,
  },
};

const SETTINGS_SCHEMA = {
  "gemini.apiKey": { category: "gemini", type: "string", label: "Gemini API 키", sensitive: true },
  "gemini.model": {
    category: "gemini",
    type: "select",
    label: "텍스트/분석 모델",
    options: ["gemini-3.1-pro-preview", "gemini-3.1-flash-lite-preview", "gemini-2.5-pro", "gemini-2.5-flash"],
  },
  "gemini.temperature": { category: "gemini", type: "slider", min: 0, max: 2, step: 0.1, label: "생성 온도" },
  "gemini.maxOutputTokens": { category: "gemini", type: "number", min: 1, max: 65536, label: "최대 출력 토큰" },
  "debate.rounds": { category: "debate", type: "number", min: 1, max: 10, label: "토론 라운드 수" },
  "debate.parallelExperts": { category: "debate", type: "boolean", label: "전문가 병렬 호출" },
  "video.model": { category: "video", type: "string", label: "Veo 모델", readOnly: true, hidden: true },
  "video.defaultDuration": { category: "video", type: "select", options: [4, 6, 8], label: "기본 영상 길이" },
  "video.aspectRatio": { category: "video", type: "select", options: ["16:9", "9:16"], label: "기본 화면비" },
  "video.resolution": { category: "video", type: "select", options: ["720p"], label: "해상도" },
  "video.maxIterations": { category: "video", type: "number", min: 1, max: 10, label: "최대 재생성 횟수" },
  "video.extensionSeconds": { category: "video", type: "number", min: 7, max: 7, readOnly: true, label: "Extension 단위(초)" },
  "video.maxTotalSeconds": { category: "video", type: "number", min: 148, max: 148, readOnly: true, label: "최대 총 길이(초)" },
  "video.postProcessingWait": { category: "video", type: "number", min: 1000, max: 120000, label: "Extension 전 대기(ms)" },
  "video.pollInterval": { category: "video", type: "number", min: 1000, max: 60000, label: "폴링 간격(ms)" },
  "video.pollTimeoutMs": { category: "video", type: "number", min: 60000, max: 3600000, label: "폴링 타임아웃(ms)" },
  "video.maxPollAttempts": { category: "video", type: "number", min: 10, max: 1000, label: "최대 폴링 시도 수" },
  "video.splitModel": {
    category: "video",
    type: "select",
    options: ["gemini-3.1-flash-lite-preview", "gemini-2.5-flash"],
    label: "시나리오 분할 모델",
    readOnly: true,
    hidden: true,
  },
  "image.model": { category: "image", type: "string", label: "Imagen 모델", readOnly: true, hidden: true },
  "image.maxReferenceSheets": { category: "image", type: "number", min: 1, max: 3, label: "레퍼런스 시트 최대 장수" },
  "ffmpeg.path": { category: "ffmpeg", type: "string", label: "ffmpeg 경로", readOnly: true, hidden: true },
  "ffmpeg.defaultCodec": { category: "ffmpeg", type: "select", options: ["libx264", "libx265"], label: "출력 코덱" },
  "ffmpeg.defaultCrf": { category: "ffmpeg", type: "slider", min: 0, max: 51, step: 1, label: "CRF" },
  "ffmpeg.defaultPreset": {
    category: "ffmpeg",
    type: "select",
    options: ["ultrafast", "superfast", "veryfast", "faster", "fast", "medium", "slow", "slower", "veryslow"],
    label: "인코딩 프리셋",
  },
  "experts.phase1.hook": { category: "experts", type: "boolean", label: "Phase1 훅" },
  "experts.phase1.story": { category: "experts", type: "boolean", label: "Phase1 스토리" },
  "experts.phase1.cta": { category: "experts", type: "boolean", label: "Phase1 CTA" },
  "experts.phase1.actionDesc": { category: "experts", type: "boolean", label: "Phase1 행동 묘사" },
  "experts.phase1.characterDesc": { category: "experts", type: "boolean", label: "Phase1 캐릭터 묘사" },
  "experts.phase3.actionEval": { category: "experts", type: "boolean", label: "Phase3 행동 평가" },
  "experts.phase3.characterEval": { category: "experts", type: "boolean", label: "Phase3 캐릭터 평가" },
  "experts.phase3.scenarioEval": { category: "experts", type: "boolean", label: "Phase3 시나리오 평가" },
  "safety.maxApiCallsPerRun": {
    category: "safety",
    type: "number",
    min: 50,
    max: 500,
    label: "Run당 최대 API 호출 수",
    readOnly: true,
    hidden: true,
  },
  "safety.maxCostPerRunUsd": {
    category: "safety",
    type: "number",
    min: 1,
    max: 100,
    label: "Run당 최대 비용(USD)",
    readOnly: true,
    hidden: true,
  },
  "safety.pipelineTimeoutMinutes": {
    category: "safety",
    type: "number",
    min: 10,
    max: 60,
    label: "파이프라인 타임아웃(분)",
    readOnly: true,
    hidden: true,
  },
};

const SETTINGS_CATEGORIES = ["gemini", "debate", "video", "image", "ffmpeg", "experts", "safety"];

module.exports = { SETTINGS_DEFAULTS, SETTINGS_SCHEMA, SETTINGS_CATEGORIES };
